# Generated by Django 5.0.14 on 2025-11-20 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces, +, -, ., parentheses).', regex='^[+0-9\\s().-]{7,20}$')]),
        ),
    ]
